package com.test.fabric;

import org.junit.Test;

import com.abs.exception.SystemException;

public class UserHelperTest {
	@Test
	public void testUserHelper() throws SystemException {
/*		System.out.println("Name: " + UserHelper.getUser().getName());
		System.out.println("Affiliation: " + UserHelper.getUser().getAffiliation());
		System.out.println("Private key: " + Hex.toHexString(UserHelper.getUser().getEnrollment().getKey().getEncoded()));
		System.out.println("Private key: " + UserHelper.getUser().getEnrollment().getKey().getAlgorithm());

		
		System.out.println("Public key: " + UserHelper.getUser().getEnrollment().getPublicKey());
		System.out.println("Cert: " + UserHelper.getUser().getEnrollment().getCert());*/
	}
}
